package com.pojo;
// Generated 14 Nov, 2017 2:59:22 PM by Hibernate Tools 4.3.1



/**
 * Airlines generated by hbm2java
 */
public class Airlines  implements java.io.Serializable {


     private Integer id;
     private String iataCode;
     private String airline;

    public Airlines() {
    }

    public Airlines(String iataCode, String airline) {
       this.iataCode = iataCode;
       this.airline = airline;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIataCode() {
        return this.iataCode;
    }
    
    public void setIataCode(String iataCode) {
        this.iataCode = iataCode;
    }
    public String getAirline() {
        return this.airline;
    }
    
    public void setAirline(String airline) {
        this.airline = airline;
    }




}


