package com.pojo;
// Generated 14 Nov, 2017 2:59:22 PM by Hibernate Tools 4.3.1



/**
 * Airports generated by hbm2java
 */
public class Airports  implements java.io.Serializable {


     private Integer id;
     private String iataCode;
     private String airport;
     private String city;
     private String state;
     private String country;
     private long latitude;
     private long longitude;

    public Airports() {
    }

    public Airports(String iataCode, String airport, String city, String state, String country, long latitude, long longitude) {
       this.iataCode = iataCode;
       this.airport = airport;
       this.city = city;
       this.state = state;
       this.country = country;
       this.latitude = latitude;
       this.longitude = longitude;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIataCode() {
        return this.iataCode;
    }
    
    public void setIataCode(String iataCode) {
        this.iataCode = iataCode;
    }
    public String getAirport() {
        return this.airport;
    }
    
    public void setAirport(String airport) {
        this.airport = airport;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public long getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(long latitude) {
        this.latitude = latitude;
    }
    public long getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(long longitude) {
        this.longitude = longitude;
    }




}


