package com.pojo;
// Generated 14 Nov, 2017 2:59:22 PM by Hibernate Tools 4.3.1



/**
 * FlightDetail generated by hbm2java
 */
public class FlightDetail  implements java.io.Serializable {


     private Integer id;
     private int year;
     private int month;
     private int day;
     private int dayOfWeek;
     private String airline;
     private String tailNumber;
     private String originAirport;
     private String destinationAirport;
     private int departureDelay;
     private int arrivalDelay;
     private int diverted;
     private int cancelled;
     private String cancellationReason;
     private int airSystemDelay;
     private int securityDelay;
     private int airlineDelay;
     private int lateAircraftDelay;
     private int weatherDelay;

    public FlightDetail() {
    }

    public FlightDetail(int year, int month, int day, int dayOfWeek, String airline, String tailNumber, String originAirport, String destinationAirport, int departureDelay, int arrivalDelay, int diverted, int cancelled, String cancellationReason, int airSystemDelay, int securityDelay, int airlineDelay, int lateAircraftDelay, int weatherDelay) {
       this.year = year;
       this.month = month;
       this.day = day;
       this.dayOfWeek = dayOfWeek;
       this.airline = airline;
       this.tailNumber = tailNumber;
       this.originAirport = originAirport;
       this.destinationAirport = destinationAirport;
       this.departureDelay = departureDelay;
       this.arrivalDelay = arrivalDelay;
       this.diverted = diverted;
       this.cancelled = cancelled;
       this.cancellationReason = cancellationReason;
       this.airSystemDelay = airSystemDelay;
       this.securityDelay = securityDelay;
       this.airlineDelay = airlineDelay;
       this.lateAircraftDelay = lateAircraftDelay;
       this.weatherDelay = weatherDelay;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public int getMonth() {
        return this.month;
    }
    
    public void setMonth(int month) {
        this.month = month;
    }
    public int getDay() {
        return this.day;
    }
    
    public void setDay(int day) {
        this.day = day;
    }
    public int getDayOfWeek() {
        return this.dayOfWeek;
    }
    
    public void setDayOfWeek(int dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }
    public String getAirline() {
        return this.airline;
    }
    
    public void setAirline(String airline) {
        this.airline = airline;
    }
    public String getTailNumber() {
        return this.tailNumber;
    }
    
    public void setTailNumber(String tailNumber) {
        this.tailNumber = tailNumber;
    }
    public String getOriginAirport() {
        return this.originAirport;
    }
    
    public void setOriginAirport(String originAirport) {
        this.originAirport = originAirport;
    }
    public String getDestinationAirport() {
        return this.destinationAirport;
    }
    
    public void setDestinationAirport(String destinationAirport) {
        this.destinationAirport = destinationAirport;
    }
    public int getDepartureDelay() {
        return this.departureDelay;
    }
    
    public void setDepartureDelay(int departureDelay) {
        this.departureDelay = departureDelay;
    }
    public int getArrivalDelay() {
        return this.arrivalDelay;
    }
    
    public void setArrivalDelay(int arrivalDelay) {
        this.arrivalDelay = arrivalDelay;
    }
    public int getDiverted() {
        return this.diverted;
    }
    
    public void setDiverted(int diverted) {
        this.diverted = diverted;
    }
    public int getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(int cancelled) {
        this.cancelled = cancelled;
    }
    public String getCancellationReason() {
        return this.cancellationReason;
    }
    
    public void setCancellationReason(String cancellationReason) {
        this.cancellationReason = cancellationReason;
    }
    public int getAirSystemDelay() {
        return this.airSystemDelay;
    }
    
    public void setAirSystemDelay(int airSystemDelay) {
        this.airSystemDelay = airSystemDelay;
    }
    public int getSecurityDelay() {
        return this.securityDelay;
    }
    
    public void setSecurityDelay(int securityDelay) {
        this.securityDelay = securityDelay;
    }
    public int getAirlineDelay() {
        return this.airlineDelay;
    }
    
    public void setAirlineDelay(int airlineDelay) {
        this.airlineDelay = airlineDelay;
    }
    public int getLateAircraftDelay() {
        return this.lateAircraftDelay;
    }
    
    public void setLateAircraftDelay(int lateAircraftDelay) {
        this.lateAircraftDelay = lateAircraftDelay;
    }
    public int getWeatherDelay() {
        return this.weatherDelay;
    }
    
    public void setWeatherDelay(int weatherDelay) {
        this.weatherDelay = weatherDelay;
    }




}


